- index.md
This mentions the cert-manager dependency and how to install it.
> Document cert-manager installation

- get-started/index.md
I added this to the bottom of the getting started page, to mirror the install section.
Fixes: #25
> docs(getting-started): add section on uninstalling

- alternate-installation-options/index.md
- get-started/index.md
> docs(operatorhub): Add OperatorHub install instructions

- _data/versions.yaml
- version/2.0.0/guides/_subsections/archive-a-recording.md
- version/2.0.0/guides/_subsections/automated-analysis.md
- version/2.0.0/guides/_subsections/common/click-create.md
- version/2.0.0/guides/_subsections/common/navigate-to-recordings.md
- version/2.0.0/guides/_subsections/common/select-target-application.md
- version/2.0.0/guides/_subsections/download-an-active-or-archived-recording.md
- version/2.0.0/guides/_subsections/download-edit-and-upload-a-customized-event-template.md
- version/2.0.0/guides/_subsections/edit-template-with-jmc.md
- version/2.0.0/guides/_subsections/re-upload-a-recording-to-archives.md
- version/2.0.0/guides/_subsections/snapshot-a-recording.md
- version/2.0.0/guides/_subsections/startstop-a-recording.md
- version/2.0.0/guides/_subsections/view-in-grafana.md
- version/2.0.0/guides/index.md
Related #36 
To prepare for additions to 2.1.0 docs, this PR duplicates the guides/ section into a 2.0.0 folder. The page content for the 2.1.0 dropdown is the same as 2.0.0.
I'll rebase my other PR for #36 on top of this one.
> docs(version): Update latest version to 2.1.0

- README.md
- _config-dev.yml
- feat(config): add -dev config overrides
- docs(readme): use hot reload, change watch, and dev override config
Fixes #61
> feat(config): add config for local development

- _includes/redhat-footer.html
- _includes/rh-analytics-footer.html
- Move "Cookie Preferences" link to RH footer
- Remove div tag from analytics footer
> feat(analytics): update cookie consent location

- _config.yml
- _layouts/home.html
Add "Sponsored by Red Hat" to the sections below to improve SEO when searching for "red hat cryostat"
- home layout
- config description
> docs(home): add Red Hat as sponsor verbiage

- get-started/index.md
> fix(getting-started): update OperatorHub.io URL

- _data/versions.yaml
- _layouts/home.html
> chore(versions): bump supported platform versions

- guides/_subsections/create-a-custom-target.md
Related to #118 
There is an invalid italic tag that causes a weird display of html tag. Fixed now.
> chore(guides): fix invalid italic tag

- _posts/2023-09-14-cryostat-231-release.md
- _posts/2023-09-18-cryostat-231-release.md
Depends on https://github.com/cryostatio/cryostat-operator/issues/623
> feat(blog): add post for 2.3.1 release

- _data/versions.yaml
- get-started/index.md
> chore(get-started): extract Cryostat Agent version property, update

- guides/index.md
> chore(guides): formatting of terms and phrases in `guides-index.md`

- guides/_subsections/automated-analysis.md
> chore(guides): update Automated Analysis guide

- guides/_subsections/configure-credentials-storage.md
- guides/_subsections/store-credentials.md
> chore(credentials): update guides around stored credentials

- guides/_subsections/snapshot-a-recording.md
> chore(snapshot): update snapshot content

- guides/_subsections/create-a-custom-target.md
See #148
I think this is the last piece required before #148 can be merged (and close #143)
> chore(custom_target): update custom target content

- guides/_subsections/using-smart-triggers.md
- guides/index.md
fixes: #143
Added documentation on Using Smart Triggers
> chore(doc): document using Smart Triggers

- guides/_subsections/using-smart-triggers.md
> chore(guides): format terms and phrases (uisng-smart-triggers.md)

- _includes/rh-analytics-head.html
- assets/javascript/tracking.js
The Matomo POC has run it's course and is being sunset. I've removed the associated code from the Cryostat site. We're currently trying to have in internal instance of Matomo that is fully supported. I'll reach out once we get it up and running.
> Matomo analytics POC being sunset

- guides/_subsections/common/card-catalog.md
- guides/_subsections/common/click-create.md
- guides/_subsections/common/layout-selector.md
- guides/_subsections/common/navigate-to-dashboard.md
- guides/_subsections/common/navigate-to-recordings.md
- guides/_subsections/common/navigate-to-settings.md
- guides/_subsections/common/navigate-to-topology.md
- guides/_subsections/common/select-a-recording.md
- guides/_subsections/common/select-target-application.md
- guides/_subsections/navigate-the-dashboard.md
- **update image versions**
- **typo**
> fix(dashboard): fix image links and a typo on dashboard guide

- guides/_subsections/getting-help.md
see [https://github.com/cryostatio/cryostatio.github.io/issues/179](https://github.com/cryostatio/cryostatio.github.io/issues/179)
> fix(getting-help.md): fix markdown formatting

- guides/_subsections/edit-template-with-jmc.md
> docs(guides): update formatting in guide for editing template using JMC

- get-started/index.md
Fixes https://github.com/cryostatio/cryostatio.github.io/issues/197
> fix(agent): recommend users use -shaded JAR by default

- guides/_subsections/create-an-automated-rule.md
See #202
Related to https://github.com/cryostatio/cryostat/pull/735
> feat(expressions): document matchexpression jfrEventTypeIds function

- get-started/index.md
> feat(autoconfig): document Agent autoconfiguration
